eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eurekaserver.us-east-2.elasticbeanstalk.com/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  cloud:
    config:
      server:
        bootstrap: true
        
server:
  port: 5000